### ISSUE TITLE
Win下 编码及路径读取问题

### ISSUE THREAD

**Issue by yj94** [a1192138141/dirScan#4]
将`fd = open(key, "r",)`
改为`fd = open(key, "r",encoding='UTF-8')`
即可解决报错 `UnicodeDecodeError: 'gbk' codec can't decode byte 0x88 in position 270: illegal multibyte sequence`

readme给的是./路径 而win下请自行改为\dir\  _需要两个\才行_

最后提一下 numpy库的问题 
python 3.9的用户 请 直接pip install numpy 安装最新版本,1.18的还不适配python 3.9

以上问题均是自己适用的 别人我不知道
工具非常好用 坐等字典更新！！！

**Comment by Degree-21** [comment]
由于使用的是mac设备，所以没有测试过windows环境下，稍后解决这个问题
